package com.smart.dto;


import com.smart.colis.src.main.java.com.smart.colis.dto.ColisDTO;
import com.smart.livraison.src.main.java.com.smart.livraison.dto.HistoriqueLivraisonDTO;
import org.junit.jupiter.api.Test;

import java.util.Collections;

import static org.junit.jupiter.api.Assertions.*;

public class ColisDTOTest {

    @Test
    public void testColisDTO() {
        // Given
        ColisDTO dto = new ColisDTO();
        
        // When
        dto.setId("1");
        dto.setDescription("Colis fragile");
        dto.setPoids(2.5);
        dto.setStatut(StatutColis.CREE);
        dto.setPriorite(PrioriteEnum.MOYENNE);
        dto.setVilleDestination("Paris");
        dto.setClientExpediteurId("client123");
        dto.setDestinataireId("dest456");
        dto.setLivreurId("livreur789");
        dto.setZoneId("zone1");
        
        HistoriqueLivraisonDTO historique = new HistoriqueLivraisonDTO();
        dto.setHistorique(Collections.singletonList(historique));

        // Then
        assertEquals("1", dto.getId());
        assertEquals("Colis fragile", dto.getDescription());
        assertEquals(2.5, dto.getPoids());
        assertEquals(StatutColis.CREE, dto.getStatut());
        assertEquals(PrioriteEnum.MOYENNE, dto.getPriorite());
        assertEquals("Paris", dto.getVilleDestination());
        assertEquals("client123", dto.getClientExpediteurId());
        assertEquals("dest456", dto.getDestinataireId());
        assertEquals("livreur789", dto.getLivreurId());
        assertEquals("zone1", dto.getZoneId());
        assertNotNull(dto.getHistorique());
        assertEquals(1, dto.getHistorique().size());
        
        // Test toString, equals, hashCode generated by Lombok
        assertNotNull(dto.toString());
        assertNotEquals(0, dto.hashCode());
        assertEquals(dto, dto);
    }
}
